### ISSUE TITLE
[BE] 1. 직접 트림 선택

### ISSUE THREAD

**Issue by Hypersand** [softeerbootcamp-2nd/A5-Idle#5]
## ✨ Description

트림 선택 페이지 정보 반환

## ✅ Tasks

- [x] 직접 트림 선택 페이지 호출 시 트림 관련 정보(트림 정보, 기본 옵션 정보) 반환
- [x] 유효하지 않은 차종으로 조회시 예외 처리
- [x] 단위 테스트

**Comment by jeongyeonKimm** [comment]
직접 트림 선택 API 구현 완료
